### ISSUE TITLE
Hyperlinks requires to open in new Tab 

### ISSUE THREAD

**Issue by Tiansing** [surpathcommunity/hacktoberfest-philippines#2]
Try to add something like <a href="#" **target="blank"**> link </a> 
to be able to direct the link in new tab, not in a current tab.

![image](https://user-images.githubusercontent.com/59194525/106085929-1a3ca680-615c-11eb-96d5-d1840d7c8012.png)

-

**Comment by vinzvinci** [comment]
We're using GitHub Markdown and this doesn't support **target="blank"**  to open new tab. But I'll look for possible answer for this.

Thanks for creating issues @Tiansing.
