### ISSUE TITLE
Portfolio's section link vinzvinci.github.io is not working

### ISSUE THREAD

**Issue by Tiansing** [surpathcommunity/hacktoberfest-philippines#4]
When I attempt to open vinzvinci.github.io this error occured! 
![144262844_424193885321907_147061636236394441_n](https://user-images.githubusercontent.com/59194525/106088135-52de7f00-6160-11eb-83d3-f0ce4317cd9e.png)

**Comment by vinzvinci** [comment]
It works now. I added`https://`, so the link will work. Thank you for raising this issue @Tiansing 

Will close the Issue now.
