### ISSUE TITLE
Cannot add labels to issues

### ISSUE THREAD

**Issue by Tiansing** [surpathcommunity/hacktoberfest-philippines#5]
The new PR and issue templates require to apply appropriate labels, but it seems that specific permissions (at least contributor AFAIK) are required for that. I think it's a common problem, and GitHub hasn't yet found a way to solve that. Have I missed something?

**Comment by vinzvinci** [comment]
You can add labels after creating issues or wait the maintainer to add it manually for you. I also create issues template to guide new  contributors.
