### ISSUE TITLE
Table isn't working well

### ISSUE THREAD

**Issue by vinzvinci** [surpathcommunity/hacktoberfest-philippines#6]
![image](https://user-images.githubusercontent.com/73097560/106536526-9a378780-6533-11eb-9e78-f44fd1e5f231.png)

**Comment by SashoStoichkov** [comment]
@vinzvinci Where is that table?

**Comment by vinzvinci** [comment]
1. You can check `index.md` for the table
2. You can check the information that we provided on `_includes` folder

> Table shows on `github-pages`

**Comment by SashoStoichkov** [comment]
I can suggest you to create:
* function (ex. JavaScript) to fill in an HTML table
* GH Action that triggers ⬆️ that function on change within `_includes` directory

**Comment by chryzcodez** [comment]
Just give me a few minutes @vinzvinci , I would make the pull request!

**Comment by chryzcodez** [comment]
> Just give me a few minutes @vinzvinci , I would make the pull request!

I would have added this symbol  ```|``` but this means the end of table in the markdown symbols that was why I used a comma```,``` !
```
| Vincent Villafuerte | vinzvinci | Founder of Surpath | Microsoft Learn Student Ambassador | BS Information System Student | Open Source DevRel | Software Engineer |
```

**Comment by Nitesh-thapliyal** [comment]
created PR do check it @vinzvinci

**Comment by vinzvinci** [comment]
- Thank you @SashoStoichkov for your suggestion, but I want to make it simple for now and maybe soon I will try that features.
~~-~~
- Hey @chryzcodez, I reviewed your PR and I don't want to use `,`  to separate my titles. I prefer the most **escaped pipes** `\|` to show this output `|` so it won't bother the table rows. Still thank you for the PR, you still get green square for the commit that you've made ^_^ .
~~-~~
- Hey @Nitesh-thapliyal. I preferred your PR, it's simple and maybe I will ignore `_includes directory` for now. Can you fix the spelling on my name, so you can get more **green square**.

> Again thanks folks, all ideas are welcome.

**Comment by Nitesh-thapliyal** [comment]
Ok sure
